#!/bin/sh
# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# docs/api is generated by `pnpm run build` (api-extractor + api-documenter) and committed.
# Run right after a build: fails when the regenerated docs differ from what is committed,
# i.e. when the source changed and docs/api was not regenerated.

CHANGES=$(git status --porcelain -- docs/)
if [ -n "$CHANGES" ]; then
    echo 'docs/api/ is out of date with the source.'
    echo 'Run `pnpm run build` locally and commit the regenerated files.'
    echo "$CHANGES"
    git --no-pager diff --stat -- docs/
    exit 1
fi
echo 'docs/api/ is up to date.'
